---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by phone.
--- DateTime: 2022/9/23 22:29
---

local stockKey='seckill:stock:' .. ARGV[1]

local orderKey='seckill:order:' .. ARGV[1]


if(tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end

if(redis.call('sismember',orderKey,ARGV[2])==1) then
    return 2
end

redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,ARGV[2])
return 0
